<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Malaysia_selectValue</name>
   <tag></tag>
   <elementGuidId>103b7607-2d8a-4e44-911c-b3c8814da58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-billing_country-result-wc61-MY']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'select2-results__option select2-results__option--highlighted' and (text() = '${country}' or . = '${country}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-billing_country-result-wc61-MY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>408a4f32-cbf4-4f38-ad89-7ea4da591c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>8e4cffd5-5ae0-4327-bb0e-fbb75e31d6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-billing_country-result-wc61-MY</value>
      <webElementGuid>15ac4d54-12c9-4eeb-9dfc-d3419d2a522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ecdb3780-74f9-4be6-a8b5-1ba9cf0afc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e3c7428-52b4-4f8a-9436-f0f09bb7a5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e1007e8f-0691-4eb1-83e3-ffe3142c7e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b1dcd73-7a0b-45a2-ace0-ad0837f5ab58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${country}</value>
      <webElementGuid>28f4b47e-5dab-4ab0-b26b-ea240e36e504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_country-result-wc61-MY&quot;)</value>
      <webElementGuid>07b79904-642e-4cf8-9056-9f2bb328ac9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-billing_country-result-wc61-MY']</value>
      <webElementGuid>d0254479-2b10-4fb5-a6a1-8d9de701d37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-billing_country-results']/li[132]</value>
      <webElementGuid>5e72e9b7-311f-41bc-84b2-25b5a54c88d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malawi'])[3]/following::li[1]</value>
      <webElementGuid>598a2866-e13c-4bd4-a9ed-f9c9c7dfe404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Madagascar'])[3]/following::li[2]</value>
      <webElementGuid>ddf098ed-5ebf-4d01-a099-1e7682f458fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maldives'])[4]/preceding::li[1]</value>
      <webElementGuid>133f4bad-5368-41ec-bf9d-61c3eee3bb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mali'])[3]/preceding::li[2]</value>
      <webElementGuid>943a77f0-a877-461e-99b4-1d1e9b38999c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[132]</value>
      <webElementGuid>1a5d2f39-066e-47d1-9d37-b8c5e494853d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-billing_country-result-wc61-MY' and (text() = 'Malaysia' or . = 'Malaysia')]</value>
      <webElementGuid>4da49349-8149-4fbb-86cc-570f90896b62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
