<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_baz</name>
   <tag></tag>
   <elementGuidId>bb219c1c-708c-4611-8581-d4db3bb910f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='285c0c60-613c-013c-411a-061cf2ecb4e3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#285c0c60-613c-013c-411a-061cf2ecb4e3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a1316acc-e192-4b6e-94da-244e95c049e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>285c0c60-613c-013c-411a-061cf2ecb4e3</value>
      <webElementGuid>4237d329-624e-4465-bd03-958193084b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button success</value>
      <webElementGuid>fdfc2910-834f-42d5-8408-6b435cf70572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>baz</value>
      <webElementGuid>a483a9ab-7761-48ba-88df-27ea12ad49dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;285c0c60-613c-013c-411a-061cf2ecb4e3&quot;)</value>
      <webElementGuid>784681b5-59c5-4127-b8de-416c9749ad03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='285c0c60-613c-013c-411a-061cf2ecb4e3']</value>
      <webElementGuid>f70a6192-caaf-4ea2-bbb8-68a2efb00350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a[3]</value>
      <webElementGuid>3c2025ea-7ecc-4aac-bafd-d35ceca20a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'baz')])[2]</value>
      <webElementGuid>77616586-1ce0-4f49-8440-45a9c1df2890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='baz'])[1]/following::a[1]</value>
      <webElementGuid>1aea6524-ada7-43f3-b01c-ac89199fd370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='foo'])[1]/following::a[2]</value>
      <webElementGuid>82525263-55c0-4439-b57c-781d7ece4763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem'])[1]/preceding::a[1]</value>
      <webElementGuid>1e1d095b-375a-4a60-a02c-f6d9a025550f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ipsum'])[1]/preceding::a[1]</value>
      <webElementGuid>38b80ea5-e105-4398-9300-700ca0851212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[4]</value>
      <webElementGuid>2a3f22b5-8f4c-4ce1-86cd-87c353319cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>5e64eb9c-8b2f-40bb-9f24-1605bbb071f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '285c0c60-613c-013c-411a-061cf2ecb4e3' and (text() = 'baz' or . = 'baz')]</value>
      <webElementGuid>4f957253-0178-4ade-8da7-42a4f68e83c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
