<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_bar</name>
   <tag></tag>
   <elementGuidId>72ccb61d-1984-4082-a2f5-03877e9c4062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='27286ce0-613c-013c-40f1-061cf2ecb4e3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#27286ce0-613c-013c-40f1-061cf2ecb4e3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df0a235e-7c08-49ce-bd42-3b583adf443e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>27286ce0-613c-013c-40f1-061cf2ecb4e3</value>
      <webElementGuid>da8fa828-7264-45c8-8011-df3d1e149aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button alert</value>
      <webElementGuid>292f16f8-9960-4b28-9f72-b326fb573954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bar</value>
      <webElementGuid>0e18dd5b-9569-4d87-ba8f-fa07382bf93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;27286ce0-613c-013c-40f1-061cf2ecb4e3&quot;)</value>
      <webElementGuid>4adc71e8-8b26-41de-8c6b-9e62bb9a96b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='27286ce0-613c-013c-40f1-061cf2ecb4e3']</value>
      <webElementGuid>b6b5c885-ce4b-4770-8def-3bb06ad609cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a[2]</value>
      <webElementGuid>51bd6fee-b6ed-415b-94b0-2e58a1ea845f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'bar')]</value>
      <webElementGuid>f3519f30-77f7-408c-acf5-65f57e814602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='foo'])[1]/following::a[1]</value>
      <webElementGuid>0797e5aa-bb53-4299-aa49-e31e37407838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Challenging DOM'])[1]/following::a[2]</value>
      <webElementGuid>54ea12f5-4a4a-40f4-97e0-7781a1b03f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='foo'])[2]/preceding::a[1]</value>
      <webElementGuid>88a1c7dc-8306-4453-a4f0-a8b3b5048064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem'])[1]/preceding::a[2]</value>
      <webElementGuid>86ce2bc0-7df3-4de0-a945-075fba022fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bar']/parent::*</value>
      <webElementGuid>70a490f9-b57b-46fa-84b6-0fe5cdeb912f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[3]</value>
      <webElementGuid>0f7c8305-b58d-4573-b86f-122bb6109691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>8cec6c8d-c8c3-4625-8947-cdbb3736a53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '27286ce0-613c-013c-40f1-061cf2ecb4e3' and (text() = 'bar' or . = 'bar')]</value>
      <webElementGuid>780f2e38-8d18-4cb2-847b-24a83aee90bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
