<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_foo_1</name>
   <tag></tag>
   <elementGuidId>ad22de63-b6de-4bb3-9c8e-753d2afdfa10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='27284e50-613c-013c-40f0-061cf2ecb4e3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#27284e50-613c-013c-40f0-061cf2ecb4e3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47ddfd68-74e8-42ca-a53a-da5d2258dc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>27284e50-613c-013c-40f0-061cf2ecb4e3</value>
      <webElementGuid>b4735f7d-dd77-41c6-bb57-29d29b855714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ad58730-5ed2-4c04-a475-45e5508f60b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>foo</value>
      <webElementGuid>4e96b7ca-ac8c-4626-8908-19d643d99d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;27284e50-613c-013c-40f0-061cf2ecb4e3&quot;)</value>
      <webElementGuid>11f4c88c-f03d-4c39-8a4a-0454d4760081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='27284e50-613c-013c-40f0-061cf2ecb4e3']</value>
      <webElementGuid>447ebbf5-f278-43f5-b477-85179ea56b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a</value>
      <webElementGuid>a00c8632-1c17-4c69-b301-79bc5e5a6f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'foo')]</value>
      <webElementGuid>01dd7f59-7dca-482d-b6c4-047db0b0ab69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Challenging DOM'])[1]/following::a[1]</value>
      <webElementGuid>3c0c13fa-33b2-4795-a2f3-1c4d6d0a6c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bar'])[1]/preceding::a[1]</value>
      <webElementGuid>6234b959-aee1-4281-9b86-70cd99141921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='foo'])[2]/preceding::a[2]</value>
      <webElementGuid>7a6aa4be-2e77-45c4-9e1f-61b7e4af6538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='foo']/parent::*</value>
      <webElementGuid>5d83fe65-ba97-4173-a279-43265a8a9203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[2]</value>
      <webElementGuid>e8cff801-d3bb-4c13-92ed-9fc760d1cec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>9d06f54a-5748-4e52-bec1-a756ba83f683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '27284e50-613c-013c-40f0-061cf2ecb4e3' and (text() = 'foo' or . = 'foo')]</value>
      <webElementGuid>0019ac69-a298-48f1-80a1-ae7a74d76dda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
