<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_qux</name>
   <tag></tag>
   <elementGuidId>b8e84ae8-44a4-4ada-a0e1-8d099a38061f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='29b811b0-613c-013c-412c-061cf2ecb4e3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#29b811b0-613c-013c-412c-061cf2ecb4e3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bffebc5a-becc-49f0-9d88-bfacfec7169c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>29b811b0-613c-013c-412c-061cf2ecb4e3</value>
      <webElementGuid>8c317b8e-01df-4059-92f6-68800c5ad4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68b8eb60-70ca-4053-ab9c-0c2e0c8412da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>qux</value>
      <webElementGuid>52fcc2f7-93d9-4958-a64c-62d8b086a6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;29b811b0-613c-013c-412c-061cf2ecb4e3&quot;)</value>
      <webElementGuid>f6501928-cf87-49ea-bf94-df16a6f4ef38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='29b811b0-613c-013c-412c-061cf2ecb4e3']</value>
      <webElementGuid>b02c51d1-1203-47f3-b53d-bb80e19ed202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a</value>
      <webElementGuid>f926664c-a4f3-434c-877b-682749debd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'qux')]</value>
      <webElementGuid>e67c2906-f023-47ba-a796-07cbcb0cd3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Challenging DOM'])[1]/following::a[1]</value>
      <webElementGuid>bed32553-7a3b-4abf-8c3b-8a850ec41136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qux'])[2]/preceding::a[1]</value>
      <webElementGuid>8b82d778-1cdf-439d-886e-e11a0eaf392d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='foo'])[1]/preceding::a[2]</value>
      <webElementGuid>01afad87-47e7-4310-a6b9-bb4d11b7af8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='qux']/parent::*</value>
      <webElementGuid>b1c72421-0b1e-4f46-8638-e16394f989f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[2]</value>
      <webElementGuid>20ae7bc5-3c86-43b9-b549-36e9fd0cc8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>00d3011c-174f-4c83-bed8-706138e11596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '29b811b0-613c-013c-412c-061cf2ecb4e3' and (text() = 'qux' or . = 'qux')]</value>
      <webElementGuid>f120e405-23d1-4878-adb9-113bed4fb6bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
