<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Phaedrum0</name>
   <tag></tag>
   <elementGuidId>95735a66-39ca-4d3a-b7f0-483402cb7ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div[2]/table/tbody/tr/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>172318c4-968a-41e0-9dbf-0beb21afe971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phaedrum0</value>
      <webElementGuid>8f6c2ecb-719e-4ecb-a6ef-3411743a749b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;large-12 columns large-centered&quot;]/div[@class=&quot;large-10 columns&quot;]/table[1]/tbody[1]/tr[1]/td[6]</value>
      <webElementGuid>82579508-ae5e-4fab-93d1-0ca6dd257edd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div[2]/table/tbody/tr/td[6]</value>
      <webElementGuid>83e2202b-8e4c-4fd7-948d-0b42286a6bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consequuntur0'])[1]/following::td[1]</value>
      <webElementGuid>aaca6e81-39db-4081-a7db-159b51b55aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Definiebas0'])[1]/following::td[2]</value>
      <webElementGuid>0740875d-c44f-4605-849a-9ef822bf7a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='edit'])[1]/preceding::td[1]</value>
      <webElementGuid>3edaaac4-8a79-4c4d-9156-36d670ebf2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='delete'])[1]/preceding::td[1]</value>
      <webElementGuid>bb364e9d-4178-49d7-b2a0-135a091c7dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Phaedrum0']/parent::*</value>
      <webElementGuid>fe3ae63f-3190-4e87-81be-e753cac722f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>47d8e4a0-d048-4151-83e8-3d8f742f0886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Phaedrum0' or . = 'Phaedrum0')]</value>
      <webElementGuid>4a9de674-6c93-4b04-9cdf-f16863dc9ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
