<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country_dropdown_opened_value</name>
   <tag></tag>
   <elementGuidId>2d104655-a71e-4619-b6d5-b1ee2b598f44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-billing_country-result-g0mg-MV']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'select2-results__option select2-results__option--highlighted' and (text() = '${country}' or . = '${country}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-billing_country-result-g0mg-MV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1738b4e4-6fbc-4821-87bb-bafde3fb77d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>51a64ecf-cc64-4dfd-8f7c-338563264bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-billing_country-result-g0mg-MV</value>
      <webElementGuid>e1f57ab2-632b-4d18-adaa-21b10c11d012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c3b95a23-789b-4aee-aadb-c3fec7d1e32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>28de55d8-a418-424f-80cd-c466e8e56ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aff488ed-33e4-4b2e-a02c-5ac6aba0e915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>749613ac-ae83-4a2b-b180-3dcbaf13f71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${country}</value>
      <webElementGuid>c4f53b8e-e450-4768-a53c-2ada4ef5a9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_country-result-g0mg-MV&quot;)</value>
      <webElementGuid>4ec49ac8-744d-42db-baeb-7e2a5268970f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-billing_country-result-g0mg-MV']</value>
      <webElementGuid>a33ce3b5-a1e5-4a6c-95e1-911fd40b17fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-billing_country-results']/li[133]</value>
      <webElementGuid>6f32ab4c-9bf3-4e99-9408-d77b985a9ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia'])[3]/following::li[1]</value>
      <webElementGuid>3a90587f-60ea-4351-8ac0-64b48958bd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malawi'])[3]/following::li[2]</value>
      <webElementGuid>4e800f49-a1a4-4303-b47d-6bb742097fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mali'])[3]/preceding::li[1]</value>
      <webElementGuid>578c4037-3429-481e-8832-e906982b4814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malta'])[3]/preceding::li[2]</value>
      <webElementGuid>08ea00ad-b2dc-4dad-b0d3-8d12916a598c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[133]</value>
      <webElementGuid>3e291c9b-5a3b-4d8d-a16c-ba182da66611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-billing_country-result-g0mg-MV' and (text() = 'Maldives' or . = 'Maldives')]</value>
      <webElementGuid>97f8d75e-574f-4892-b6c2-bf9139838472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
